# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Ud6iRL_gf3EZSxqpXUO0m4m8FE65xAs
"""

x = 5
print(f"變數x的值是:{x}")
print(f"變數x的記憶體地址是:{id(x)}")